substitutions:
  devicename: growatt13kw
  mqqt_topic: 'sensors'
  device_unique_id: growatt13kw

esphome:
  name: $devicename

esp8266:
  board: d1_mini

# disable logger
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxx"

# Enable ota. Uncomment passwort if you need
ota:
- platform: esphome
  password: !secret ota

# uncomment, if you use dallas sensor
#dallas: #dallas conmponent is replace by the "one_wire" TODO!
#  - pin: GPIO04

mqtt:
  broker: !secret mqtt_url
  username: !secret mqtt_user
  password: !secret mqtt_pass
  topic_prefix: $mqqt_topic/$devicename

  birth_message:
    topic: $mqqt_topic/$devicename/status
    payload: online
  will_message:
    topic: $mqqt_topic/$devicename/status
    payload: offline
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: xx.xx.xx.xx
    # Set this to the IP address of the router. Often ends with .1
    gateway: xx.xx.xx.xx
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Growatt13kW Fallback Hotspot"
    password: "xxxxxxxx"

captive_portal:
  
uart:
#  - id: uart1
    baud_rate: 9600
    tx_pin: TX
    rx_pin: RX

modbus:
#  uart_id: uart1
  flow_control_pin: D0

sensor:
  - platform: growatt_solar
    update_interval: 10s
    protocol_version: RTU2

    inverter_status:
      name: Growatt Status Code $device_unique_id

    phase_a:
      voltage:
          name: Growatt Voltage Phase A $device_unique_id
      current:
          name: Growatt Current Phase A $device_unique_id
      active_power:
          name: Growatt Power Phase A $device_unique_id

    pv1:
      voltage:
          name: Growatt PV1 Voltage $device_unique_id
      current:
          name: Growatt PV1 Current $device_unique_id
      active_power:
          name: Growatt PV1 Active Power $device_unique_id

    active_power:
      name: Growatt Grid Active Power $device_unique_id

    pv_active_power:
      name: Growatt PV Active Power $device_unique_id

    frequency:
      name: Growatt Frequency $device_unique_id

    energy_production_day:
      name: Growatt Today's Generation $device_unique_id

    total_energy_production:
      name: Growatt Total Energy Production $device_unique_id
      device_class: energy
      unit_of_measurement: kWh
      state_class: "total_increasing"
      accuracy_decimals: 3

    inverter_module_temp:
      name: Growatt Inverter Module Temp $device_unique_id

# If you use Dallas Sensor, put your dallas Sensor ID hier
# to get the sensor ID see: https://esphome.io/components/sensor/dallas.html#getting-sensor-ids
# see log output in WEB UI ESPHome: 
# [D][dallas.sensor:082]:   Found sensors:
# [D][dallas.sensor:084]:     0x1c0000031edd2a28
# --------------------END OF DESCRIPTION -------------------------------
#  - platform: dallas
#    address: 0xa60000001ebd8428    
#    name: "Growatt USB Temperature"
